version: '3.9'

networks:
  web-network:
    driver: 'bridge'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    environment:
      - DATABASE_HOST=host.docker.internal
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - ${EUROGAMER_APP_PORT}:${EUROGAMER_APP_PORT}
    depends_on:
      - db
    networks:
      - web-network
  db:
    image: mysql:8
    container_name: eurogamer-db
    restart: unless-stopped
    command: --default-authentication-plugin=caching_sha2_password
    ports:
      - ${EUROGAMER_DB_PORT}:${EUROGAMER_DB_PORT}
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $EUROGAMER_DB_PASSWORD
      MYSQL_DATABASE: $EUROGAMER_DB_NAME
      MYSQL_USER: $EUROGAMER_DB_USERNAME
      MYSQL_PASSWORD: $EUROGAMER_DB_PASSWORD
    env_file: ./.env
    networks:
      - web-network
  test-db:
    image: mysql:8
    restart: always
    ports:
      - ${EUROGAMER_DB_PORT}:${EUROGAMER_DB_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: $EUROGAMER_DB_PASSWORD
    profiles:
      - test
